version: '3.8'
services:
  frontend:
    container_name: devplus-fe
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
