export enum QUERY_KEY {
	LIST_WORKSPACE = 'LIST_WORKSPACE',
	DETAIL_WORKSPACE = 'DETAIL_WORKSPACE',
	ACCEPT_WORKSPACE = 'ACCEPT_WORKSPACE',
	CREATE_WORKSPACE = 'CREATE_WORKSPACE',
	UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN',
	FIND_ONE_CAMPAIGN = 'FIND_ONE_CAMPAIGN',
	CREATE_CAMPAIGN = 'CREATE_CAMPAIGN',
	LIST_CAMPAIGN = 'LIST_CAMPAIGN',
}
